mongo:
  image: mongo:3.5.12
  ports:
    - 27018:27017
  volumes:
    - ./db_server_test:/data/db
mongo-express:
    image: "mongo-express:latest"
    ports:
    - "8082:8081"
    links:
     - mongo