version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0-browsers
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test:client
